/********************************************************************/
/*                                                                  */
/*  chkccomp   Check properties of C compiler and runtime.          */
/*  Copyright (C) 2010 - 2014  Thomas Mertes                        */
/*                                                                  */
/*  This program is free software; you can redistribute it and/or   */
/*  modify it under the terms of the GNU General Public License as  */
/*  published by the Free Software Foundation; either version 2 of  */
/*  the License, or (at your option) any later version.             */
/*                                                                  */
/*  This program is distributed in the hope that it will be useful, */
/*  but WITHOUT ANY WARRANTY; without even the implied warranty of  */
/*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the   */
/*  GNU General Public License for more details.                    */
/*                                                                  */
/*  You should have received a copy of the GNU General Public       */
/*  License along with this program; if not, write to the           */
/*  Free Software Foundation, Inc., 51 Franklin Street,             */
/*  Fifth Floor, Boston, MA  02110-1301, USA.                       */
/*                                                                  */
/*  Module: Chkccomp                                                */
/*  File: seed7/src/chkccomp.c                                      */
/*  Changes: 2010 - 2014  Thomas Mertes                             */
/*  Content: Program to Check properties of C compiler and runtime. */
/*                                                                  */
/********************************************************************/

#include "version.h"

/**
 *  From version.h the following defines are used (for details see: read_me.txt):
 *
 *  os_off_t
 *      Type used for os_fseek(), os_ftell(), offsetSeek(), offsetTell()
 *      and seekFileLength().
 *  TURN_OFF_FP_EXCEPTIONS
 *      Use the function _control87() to turn off floating point exceptions.
 *  DEFINE_MATHERR_FUNCTION
 *      Define the function _matherr() which handles floating point errors.
 *  PATH_DELIMITER:
 *      Path delimiter character used by the command shell of the operating system.
 *  QUOTE_WHOLE_SHELL_COMMAND:
 *      Defined when shell commands, starting with " need to be quoted a again.
 *  OBJECT_FILE_EXTENSION:
 *      The extension used by the C compiler for object files.
 *  EXECUTABLE_FILE_EXTENSION:
 *      The extension which is used by the operating system for executables.
 *  C_COMPILER:
 *      Contains the command to call the stand-alone C compiler and linker.
 *  CC_NO_OPT_OUTPUT_FILE:
 *      Defined, when compiling and linking with one command cannot use -o.
 *  REDIRECT_C_ERRORS:
 *      The redirect command to redirect the errors of the C compiler to a file.
 *  LINKER_OPT_OUTPUT_FILE:
 *      Contains the linker option to provide the output filename (e.g.: "-o ").
 */

#include "stdlib.h"
#include "string.h"
#include "stdio.h"
#include "stddef.h"
#include "time.h"
#include "float.h"
#include "math.h"
#include "sys/types.h"
#include "sys/stat.h"

#include "config.h"

/**
 *  From config.h the following defines are used (for details see: read_me.txt):
 *
 *  MAP_ABSOLUTE_PATH_TO_DRIVE_LETTERS
 *      Map absolute paths to operating system paths with drive letter.
 */

#include "chkccomp.h"

/**
 *  The file chkccomp.h is NOT part of the Seed7 release.
 *  Instead chkccomp.h is generated by the makefile and
 *  removed after chkccomp was compiled and executed.
 *  In chkccomp.h the following macros might be defined:
 *
 *  mkdir(path,mode)
 *      Macro to replace the Posix function mkdir.
 *      E.g.: #define mkdir(path,mode) mkdir(path)
 *            #define mkdir(path,mode) _mkdir(path)
 *  rmdir
 *      Name of Posix function rmdir.
 *      E.g.: #define rmdir _rmdir
 *  WRITE_CC_VERSION_INFO
 *      Write the version of the C compiler to the file "cc_vers.txt".
 *      E.g.: #define WRITE_CC_VERSION_INFO system("$(GET_CC_VERSION_INFO) cc_vers.txt");
 *  LIST_DIRECTORY_CONTENTS
 *      Either "ls" or "dir".
 *      E.g.: #define LIST_DIRECTORY_CONTENTS "ls"
 *            #define LIST_DIRECTORY_CONTENTS "dir"
 *  The macros described above are only used in the program chkccomp.
 *  This macros are not used in the Seed7 Interpreter (s7) or in the
 *  Seed7 Runtime Library.
 */


#ifndef EXECUTABLE_FILE_EXTENSION
#define EXECUTABLE_FILE_EXTENSION ""
#endif

#ifndef S_ISREG
#define S_ISREG(mode) (((mode) & S_IFMT) == S_IFREG)
#endif

#ifndef S_ISDIR
#define S_ISDIR(mode) (((mode) & S_IFMT) == S_IFDIR)
#endif

#define xstr(s) str(s)
#define str(s) #s

char c_compiler[1024];

static const int alignmentTable[] = {
    6, 0, 1, 0, 2, 0, 1, 0, 3, 0, 1, 0, 2, 0, 1, 0,
    4, 0, 1, 0, 2, 0, 1, 0, 3, 0, 1, 0, 2, 0, 1, 0,
    5, 0, 1, 0, 2, 0, 1, 0, 3, 0, 1, 0, 2, 0, 1, 0,
    4, 0, 1, 0, 2, 0, 1, 0, 3, 0, 1, 0, 2, 0, 1, 0,
  };

char *stack_base;



#ifdef DEFINE_MATHERR_FUNCTION
int _matherr (struct _exception *a)

  { /* _matherr */
    a->retval = a->retval;
    return 1;
  } /* _matherr */
#endif



void prepareCompileCommand (void)

  {
    int pos;
    int quote_command = 0;
    int len;

  /* prepareCompileCommand */
    strcpy(c_compiler, C_COMPILER);
#ifdef MAP_ABSOLUTE_PATH_TO_DRIVE_LETTERS
    if (c_compiler[0] == '/') {
      c_compiler[0] = c_compiler[1];
      c_compiler[1] = ':';
    } /* if */
#endif
    for (pos = 0; c_compiler[pos] != '\0'; pos++) {
      if (c_compiler[pos] == '/') {
        c_compiler[pos] = PATH_DELIMITER;
      } else if (c_compiler[pos] == ' ') {
        quote_command = 1;
      } /* if */
    } /* for */
    if (quote_command) {
      len = strlen(c_compiler);
      memmove(&c_compiler[1], c_compiler, len);
      c_compiler[0] = '\"';
      c_compiler[len + 1] = '\"';
      c_compiler[len + 2] = '\0';
    } /* if */
  } /* prepareCompileCommand */



int fileIsRegular (const char *fileName)

  {
    struct stat stat_buf;

  /* fileIsRegular */
    return stat(fileName, &stat_buf) == 0 && S_ISREG(stat_buf.st_mode);
  } /* fileIsRegular */



int fileIsDir (const char *fileName)

  {
    struct stat stat_buf;

  /* fileIsDir */
    return stat(fileName, &stat_buf) == 0 && S_ISDIR(stat_buf.st_mode);
  } /* fileIsDir */



void cleanUpCompilation (void)

  {
    char fileName[1024];

  /* cleanUpCompilation */
    if (fileIsRegular("ctest.c")) {
      remove("ctest.c");
    } /* if */
    if (fileIsRegular("ctest.cerrs")) {
      remove("ctest.cerrs");
    } /* if */
    if (fileIsRegular("ctest.lerrs")) {
      remove("ctest.lerrs");
    } /* if */
    sprintf(fileName, "ctest%s", OBJECT_FILE_EXTENSION);
    if (fileIsRegular(fileName)) {
      remove(fileName);
    } /* if */
    sprintf(fileName, "ctest%s", EXECUTABLE_FILE_EXTENSION);
    if (fileIsRegular(fileName)) {
      remove(fileName);
    } /* if */
    if (fileIsRegular("ctest.out")) {
      remove("ctest.out");
    } /* if */
  } /* cleanUpCompilation */



int doCompileAndLink (const char *options)

  {
    char command[1024];
    int len;
    char fileName[1024];
    int returncode;
    int result = 0;

  /* doCompileAndLink */
#ifdef CC_FLAGS
    sprintf(command, "%s %s %s ctest.c", c_compiler, options, CC_FLAGS);
#else
    sprintf(command, "%s %s ctest.c", c_compiler, options);
#endif
#if defined LINKER_OPT_OUTPUT_FILE && !defined CC_NO_OPT_OUTPUT_FILE
    sprintf(&command[strlen(command)], " %sctest%s",
            LINKER_OPT_OUTPUT_FILE, EXECUTABLE_FILE_EXTENSION);
#endif
#ifdef REDIRECT_C_ERRORS
    sprintf(&command[strlen(command)], " %sctest.cerrs",
            REDIRECT_C_ERRORS);
#endif
#ifdef QUOTE_WHOLE_SHELL_COMMAND
    if (command[0] == '\"') {
      len = strlen(command);
      memmove(&command[1], command, len);
      command[0] = '\"';
      command[len + 1] = '\"';
      command[len + 2] = '\0';
    } /* if */
#endif
    returncode = system(command);
    sprintf(fileName, "ctest%s", EXECUTABLE_FILE_EXTENSION);
    if (fileIsRegular(fileName)) {
      if (returncode == 0) {
        result = 1;
      } else {
        /* printf(" *** The compiler %s fails, but creates an executable.", c_compiler); */
      } /* if */
    } /* if */
#ifdef DEBUG_CHKCCOMP
    printf("command: %s\n", command);
    printf("returncode: %d\n", returncode);
    printf("result: %d\n", result);
#endif
    return result;
  } /* doCompileAndLink */



int compileAndLinkWithOptionsOk (const char *content, const char *options)

  {
    FILE *testFile;
    int result = 0;

  /* compileAndLinkWithOptionsOk */
    /* printf("compileAndLinkWithOptionsOk(%s)\n", content); */
    cleanUpCompilation();
    testFile = fopen("ctest.c", "w");
    if (testFile != NULL) {
      fprintf(testFile, "%s", content);
      fclose(testFile);
      result = doCompileAndLink(options);
    } /* if */
#ifdef DEBUG_CHKCCOMP
    printf("content: %s\n", content);
#endif
    return result;
  } /* compileAndLinkWithOptionsOk */



int compileAndLinkOk (const char *content)

  { /* compileAndLinkOk */
    return compileAndLinkWithOptionsOk(content, "");
  } /* compileAndLinkOk */



int doTest (void)

  {
    char command[1024];
    FILE *outFile;
    int result = -1;

  /* doTest */
    sprintf(command, ".%cctest%s>ctest.out", PATH_DELIMITER, EXECUTABLE_FILE_EXTENSION);
    if (system(command) != -1 && (outFile = fopen("ctest.out", "r")) != NULL) {
      fscanf(outFile, "%d", &result);
      fclose(outFile);
    } /* if */
    return result;
  } /* doTest */



/**
 *  Determine if DEFINE_OS_ENVIRON or INITIALIZE_OS_ENVIRON must be defined.
 */
void determineEnvironDefines (FILE *versionFile)

  {
    char buffer[4096];
    int define_os_environ = 0;

  /* determineEnvironDefines */
    buffer[0] = '\0';
    if (compileAndLinkOk("#include <stdlib.h>\n#include \"version.h\"\n"
                         "int main(int argc,char *argv[])"
                         "{os_environ;return 0;}\n")) {
      strcat(buffer, "#include <stdlib.h>\n");
    } else if (compileAndLinkOk("#include <unistd.h>\n#include \"version.h\"\n"
                                "int main(int argc,char *argv[])"
                                "{os_environ;return 0;}\n")) {
      strcat(buffer, "#include <unistd.h>\n");
    } else {
      fprintf(versionFile, "#define DEFINE_OS_ENVIRON\n");
      define_os_environ = 1;
    } /* if */
    strcat(buffer, "#include <stdio.h>\n");
    strcat(buffer, "#include \"version.h\"\n");
#ifdef OS_STRI_WCHAR
    strcat(buffer, "typedef wchar_t *os_striType;\n");
#else
    strcat(buffer, "typedef char *os_striType;\n");
#endif
    if (define_os_environ) {
      strcat(buffer, "extern os_striType *os_environ;\n");
    } /* if */
#ifdef USE_WMAIN
    strcat(buffer, "int wmain(int argc,wchar_t *argv[])");
#else
    strcat(buffer, "int main(int argc,char *argv[])");
#endif
    strcat(buffer, "{printf(\"%d\\n\",os_environ==(os_striType *)0);return 0;}\n");
    if (!compileAndLinkOk(buffer) || doTest() == 1) {
      fputs("#define INITIALIZE_OS_ENVIRON\n", versionFile);
    } /* if */
  } /* determineEnvironDefines */



void numericSizes (FILE *versionFile)

  {
    int testResult;

  /* numericSizes */
    printf("Numeric sizes:");
    fflush(stdout);
    fprintf(versionFile, "#define SHORT_SIZE %lu\n",    (long unsigned) (8 * sizeof(short)));
    fprintf(versionFile, "#define INT_SIZE %lu\n",      (long unsigned) (8 * sizeof(int)));
    fprintf(versionFile, "#define LONG_SIZE %lu\n",     (long unsigned) (8 * sizeof(long)));
    if (compileAndLinkOk("#include <stdio.h>\nint main(int argc, char *argv[])"
                         "{printf(\"%d\\n\",sizeof(long long));return 0;}\n")) {
      testResult = doTest();
      if (testResult != -1) {
        fprintf(versionFile, "#define LONG_LONG_SIZE %lu\n",     (long unsigned) (8 * testResult));
      } /* if */
    } /* if */
    fprintf(versionFile, "#define POINTER_SIZE %lu\n",  (long unsigned) (8 * sizeof(char *)));
    fprintf(versionFile, "#define FLOAT_SIZE %lu\n",    (long unsigned) (8 * sizeof(float)));
    fprintf(versionFile, "#define DOUBLE_SIZE %lu\n",   (long unsigned) (8 * sizeof(double)));
    fprintf(versionFile, "#define WCHAR_T_SIZE %lu\n",  (long unsigned) (8 * sizeof(wchar_t)));
    fprintf(versionFile, "#define OS_OFF_T_SIZE %lu\n", (long unsigned) (8 * sizeof(os_off_t)));
    fprintf(versionFile, "#define TIME_T_SIZE %lu\n",   (long unsigned) (8 * sizeof(time_t)));
    if ((time_t) -1 < 0) {
      fputs("#define TIME_T_SIGNED\n", versionFile);
    } /* if */
    if ((size_t) -1 < 0) {
      fputs("#define SIZE_T_SIGNED\n", versionFile);
    } /* if */
    if (sizeof(int) == 4) {
      fputs("#define INT32TYPE int\n", versionFile);
      fputs("#define INT32TYPE_STRI \"int\"\n", versionFile);
      fputs("#define UINT32TYPE unsigned int\n", versionFile);
      fputs("#define UINT32TYPE_STRI \"unsigned int\"\n", versionFile);
    } else if (sizeof(long) == 4) {
      fputs("#define INT32TYPE long\n", versionFile);
      fputs("#define INT32TYPE_STRI \"long\"\n", versionFile);
      fputs("#define UINT32TYPE unsigned long\n", versionFile);
      fputs("#define UINT32TYPE_STRI \"unsigned long\"\n", versionFile);
      fputs("#define INT32TYPE_SUFFIX_L\n", versionFile);
      fputs("#define INT32TYPE_FORMAT_L\n", versionFile);
    } /* if */
    if (sizeof(long) == 8) {
      fputs("#define INT64TYPE long\n", versionFile);
      fputs("#define INT64TYPE_STRI \"long\"\n", versionFile);
      fputs("#define UINT64TYPE unsigned long\n", versionFile);
      fputs("#define UINT64TYPE_STRI \"unsigned long\"\n", versionFile);
      if (compileAndLinkOk("#include <stdio.h>\nint main(int argc, char *argv[])"
                           "{long long n=12345678L;printf(\"%d\\n\",sizeof(1L));return 0;}\n") && doTest() == 8) {
        fputs("#define INT64TYPE_SUFFIX_L\n", versionFile);
      } /* if */
      fputs("#define INT64TYPE_FORMAT_L\n", versionFile);
    } else if (compileAndLinkOk("#include <stdio.h>\nint main(int argc, char *argv[])"
                                "{printf(\"%d\\n\",sizeof(long long));return 0;}\n") && doTest() == 8) {
      /* The type long long is defined and it is a 64-bit type */
      fputs("#define INT64TYPE long long\n", versionFile);
      fputs("#define INT64TYPE_STRI \"long long\"\n", versionFile);
      fputs("#define UINT64TYPE unsigned long long\n", versionFile);
      fputs("#define UINT64TYPE_STRI \"unsigned long long\"\n", versionFile);
      if (compileAndLinkOk("#include <stdio.h>\nint main(int argc, char *argv[])"
                           "{long long n=12345678LL;printf(\"%d\\n\",sizeof(1LL));return 0;}\n") && doTest() == 8) {
        fputs("#define INT64TYPE_SUFFIX_LL\n", versionFile);
      } /* if */
      if (compileAndLinkOk("#include <stdio.h>\nint main(int argc, char *argv[])\n"
                           "{char b[99]; sprintf(b, \"A%lldB\", (long long) 1 << 32);\n"
                           "printf(\"%d\\n\", strcmp(b,\"A4294967296B\")==0);return 0;}\n") && doTest() == 1) {
        fputs("#define INT64TYPE_FORMAT_LL\n", versionFile);
      } else if (compileAndLinkOk("#include <stdio.h>\nint main(int argc, char *argv[])\n"
                                  "{char b[99]; sprintf(b, \"A%LdB\", (long long) 1 << 32);\n"
                                  "printf(\"%d\\n\", strcmp(b,\"A4294967296B\")==0);return 0;}\n") && doTest() == 1) {
        fputs("#define INT64TYPE_FORMAT_CAPITAL_L\n", versionFile);
      } else if (compileAndLinkOk("#include <stdio.h>\nint main(int argc, char *argv[])\n"
                                  "{char b[99]; sprintf(b, \"A%I64dB\", (long long) 1 << 32);\n"
                                  "printf(\"%d\\n\", strcmp(b,\"A4294967296B\")==0);return 0;}\n") && doTest() == 1) {
        fputs("#define INT64TYPE_FORMAT_I64\n", versionFile);
      } /* if */
    } else if (compileAndLinkOk("#include <stdio.h>\nint main(int argc, char *argv[])\n"
                                "{printf(\"%d\\n\",sizeof(__int64));return 0;}\n") && doTest() == 8) {
      /* The type __int64 is defined and it is a 64-bit type */
      fputs("#define INT64TYPE __int64\n", versionFile);
      fputs("#define INT64TYPE_STRI \"__int64\"\n", versionFile);
      fputs("#define UINT64TYPE unsigned __int64\n", versionFile);
      fputs("#define UINT64TYPE_STRI \"unsigned __int64\"\n", versionFile);
      if (compileAndLinkOk("#include <stdio.h>\nint main(int argc, char *argv[])"
                           "{__int64 n=12345678LL;printf(\"%d\\n\",sizeof(1LL));return 0;}\n") && doTest() == 8) {
        fputs("#define INT64TYPE_SUFFIX_LL\n", versionFile);
      } /* if */
      if (compileAndLinkOk("#include <stdio.h>\nint main(int argc, char *argv[])\n"
                           "{char b[99]; sprintf(b, \"A%lldB\", (__int64) 1 << 32);\n"
                           "printf(\"%d\\n\", strcmp(b,\"A4294967296B\")==0);return 0;}\n") && doTest() == 1) {
        fputs("#define INT64TYPE_FORMAT_LL\n", versionFile);
      } else if (compileAndLinkOk("#include <stdio.h>\nint main(int argc, char *argv[])\n"
                                  "{char b[99]; sprintf(b, \"A%LdB\", (__int64) 1 << 32);\n"
                                  "printf(\"%d\\n\", strcmp(b,\"A4294967296B\")==0);return 0;}\n") && doTest() == 1) {
        fputs("#define INT64TYPE_FORMAT_CAPITAL_L\n", versionFile);
      } else if (compileAndLinkOk("#include <stdio.h>\nint main(int argc, char *argv[])\n"
                                  "{char b[99]; sprintf(b, \"A%I64dB\", (__int64) 1 << 32);\n"
                                  "printf(\"%d\\n\", strcmp(b,\"A4294967296B\")==0);return 0;}\n") && doTest() == 1) {
        fputs("#define INT64TYPE_FORMAT_I64\n", versionFile);
      } /* if */
    } /* if */
    if (compileAndLinkOk("#include <stdio.h>\n#include <time.h>\n"
                         "int main(int argc, char *argv[])\n"
                         "{__int128 a = (__int128) time(NULL) * (__int128) clock();\n"
                         "if (sizeof(__int128)==sizeof(unsigned __int128))\n"
                         "printf(\"%d\\n\",sizeof(__int128));\n"
                         "else printf(\"0\\n\");return 0;}\n") && doTest() == 16) {
      /* The type __int128 is defined and it is a 128-bit type */
      fputs("#define INT128TYPE __int128\n", versionFile);
      fputs("#define INT128TYPE_STRI \"__int128\"\n", versionFile);
      fputs("#define UINT128TYPE unsigned __int128\n", versionFile);
      fputs("#define UINT128TYPE_STRI \"unsigned __int128\"\n", versionFile);
    } else if (compileAndLinkOk("#include <stdio.h>\n#include <time.h>\n"
                                "int main(int argc, char *argv[])\n"
                                "{__int128 a = (__int128) time(NULL) * (__int128) clock();\n"
                                "if (sizeof(__int128_t)==sizeof(__uint128_t))\n"
                                "printf(\"%d\\n\",sizeof(__int128_t));\n"
                                "else printf(\"0\\n\");return 0;}\n") && doTest() == 16) {
      /* The type __int128_t is defined and it is a 128-bit type */
      fputs("#define INT128TYPE __int128_t\n", versionFile);
      fputs("#define INT128TYPE_STRI \"__int128_t\"\n", versionFile);
      fputs("#define UINT128TYPE __uint128_t\n", versionFile);
      fputs("#define UINT128TYPE_STRI \"__uint128_t\"\n", versionFile);
    } /* if */
    printf(" determined\n");
  } /* numericSizes */



void numericProperties (FILE *versionFile)

  {
    int testResult;
    long number;
    char buffer[4096];
    int zero_divide_triggers_signal = 0;
    float zero = 0.0;
    float negativeZero;
    float minusZero;
    float nanValue1;
    float nanValue2;
    float plusInf;
    float minusInf;
    int floatRadixFactor;

  /* numericProperties */
    printf("Numeric properties:");
    fflush(stdout);
    number = -1;
    if (number >> 1 == (long) -1) {
      fputs("#define RSHIFT_DOES_SIGN_EXTEND\n", versionFile);
    } /* if */
    if (~number == (long) 0) {
      fputs("#define TWOS_COMPLEMENT_INTTYPE\n", versionFile);
    } else if (~number == (long) 1) {
      fputs("#define ONES_COMPLEMENT_INTTYPE\n", versionFile);
    } /* if */
    number = 1;
    if (((char *) &number)[0] == 1) {
      fputs("#define LITTLE_ENDIAN_INTTYPE\n", versionFile);
    } else {
      fputs("#define BIG_ENDIAN_INTTYPE\n", versionFile);
    } /* if */
#ifdef INT_DIV_BY_ZERO_POPUP
    fputs("#define CHECK_INT_DIV_BY_ZERO\n", versionFile);
#else
    if (!compileAndLinkOk("#include<stdio.h>\n"
                          "int main(int argc,char *argv[]){"
                          "printf(\"%d\\n\", 1/0);return 0;}\n") ||
        !compileAndLinkOk("#include<stdlib.h>\n#include<stdio.h>\n#include<signal.h>\n"
                          "void handleSigfpe(int sig){puts(\"2\");exit(0);}\n"
                          "void handleSigill(int sig){puts(\"3\");exit(0);}\n"
                          "int main(int argc,char *argv[]){\n"
                          "signal(SIGFPE,handleSigfpe);\n"
                          "signal(SIGILL,handleSigill);\n"
                          "printf(\"%d\\n\",1/0==0);return 0;}\n") || doTest() != 2 ||
        !compileAndLinkOk("#include<stdlib.h>\n#include<stdio.h>\n#include<signal.h>\n"
                          "void handleSigfpe(int sig){puts(\"2\");exit(0);}\n"
                          "void handleSigill(int sig){puts(\"3\");exit(0);}\n"
                           "int main(int argc,char *argv[]){\n"
                          "int zero=0;\n"
                          "signal(SIGFPE,handleSigfpe);\n"
                          "signal(SIGILL,handleSigill);\n"
                          "printf(\"%d\\n\",1/zero==0);return 0;}\n") || doTest() != 2 ||
        !compileAndLinkOk("#include<stdlib.h>\n#include<stdio.h>\n#include<signal.h>\n"
                          "void handleSigfpe(int sig){puts(\"2\");exit(0);}\n"
                          "void handleSigill(int sig){puts(\"3\");exit(0);}\n"
                           "int main(int argc,char *argv[]){\n"
                          "signal(SIGFPE,handleSigfpe);\n"
                          "signal(SIGILL,handleSigill);\n"
                          "printf(\"%d\\n\",0/0==0);return 0;}\n") || doTest() != 2 ||
        !compileAndLinkOk("#include<stdlib.h>\n#include<stdio.h>\n#include<signal.h>\n"
                          "void handleSigfpe(int sig){puts(\"2\");exit(0);}\n"
                          "void handleSigill(int sig){puts(\"3\");exit(0);}\n"
                           "int main(int argc,char *argv[]){\n"
                          "int zero=0;\n"
                          "signal(SIGFPE,handleSigfpe);\n"
                          "signal(SIGILL,handleSigill);\n"
                          "printf(\"%d\\n\",0/zero==0);return 0;}\n") || doTest() != 2) {
      fputs("#define CHECK_INT_DIV_BY_ZERO\n", versionFile);
    } else {
      fputs("#define INT_DIV_BY_ZERO_SIGNALS\n", versionFile);
#ifndef DO_SIGFPE_WITH_DIV_BY_ZERO
      fputs("#define DO_SIGFPE_WITH_DIV_BY_ZERO\n", versionFile);
#endif
    } /* if */
    if (!compileAndLinkOk("#include<stdio.h>\n"
                          "int main(int argc,char *argv[]){"
                          "printf(\"%d\\n\", 1%0);return 0;}\n") ||
        !compileAndLinkOk("#include<stdlib.h>\n#include<stdio.h>\n#include<signal.h>\n"
                          "void handleSigfpe(int sig){puts(\"2\");exit(0);}\n"
                          "void handleSigill(int sig){puts(\"3\");exit(0);}\n"
                          "int main(int argc,char *argv[]){\n"
                          "int zero=0;\n"
                          "signal(SIGFPE,handleSigfpe);\n"
                          "signal(SIGILL,handleSigill);\n"
                          "printf(\"%d\\n\",1%zero==0);return 0;}\n") || doTest() != 2 ||
        !compileAndLinkOk("#include<stdlib.h>\n#include<stdio.h>\n#include<signal.h>\n"
                          "void handleSigfpe(int sig){puts(\"2\");exit(0);}\n"
                          "void handleSigill(int sig){puts(\"3\");exit(0);}\n"
                           "int main(int argc,char *argv[]){\n"
                          "int one=0, zero=0;\n"
                          "signal(SIGFPE,handleSigfpe);\n"
                          "signal(SIGILL,handleSigill);\n"
                          "printf(\"%d\\n\",one%zero==0);return 0;}\n") || doTest() != 2 ||
        !compileAndLinkOk("#include<stdlib.h>\n#include<stdio.h>\n#include<signal.h>\n"
                          "void handleSigfpe(int sig){puts(\"2\");exit(0);}\n"
                          "void handleSigill(int sig){puts(\"3\");exit(0);}\n"
                           "int main(int argc,char *argv[]){\n"
                          "int zero1=0, zero2=0;\n"
                          "signal(SIGFPE,handleSigfpe);\n"
                          "signal(SIGILL,handleSigill);\n"
                          "printf(\"%d\\n\",zero1%zero2==0);return 0;}\n") || doTest() != 2) {
      fputs("#define CHECK_INT_REM_BY_ZERO\n", versionFile);
    } /* if */
    if (!compileAndLinkOk("#include<stdlib.h>\n#include<stdio.h>\n#include<signal.h>\n"
                          "void handleSigfpe(int sig){puts(\"2\");exit(0);}\n"
                          "void handleSigill(int sig){puts(\"3\");exit(0);}\n"
                           "int main(int argc,char *argv[]){\n"
                          "signal(SIGFPE,handleSigfpe);\n"
                          "signal(SIGILL,handleSigill);\n"
                          "printf(\"%d\\n\",0%0==0);return 0;}\n") || doTest() != 2 ||
        !compileAndLinkOk("#include<stdlib.h>\n#include<stdio.h>\n#include<signal.h>\n"
                          "void handleSigfpe(int sig){puts(\"2\");exit(0);}\n"
                          "void handleSigill(int sig){puts(\"3\");exit(0);}\n"
                           "int main(int argc,char *argv[]){\n"
                          "int zero=0;\n"
                          "signal(SIGFPE,handleSigfpe);\n"
                          "signal(SIGILL,handleSigill);\n"
                          "printf(\"%d\\n\",0%zero==0);return 0;}\n") || doTest() != 2) {
      fputs("#define CHECK_INT_REM_ZERO_BY_ZERO\n", versionFile);
    } /* if */
#endif
#ifdef TURN_OFF_FP_EXCEPTIONS
    _control87(MCW_EM, MCW_EM);
#endif
    sprintf(buffer, "%1.0f %1.0f %1.0f %1.1f %1.1f %1.2f %1.2f %1.0f %1.0f %1.0f %1.1f %1.1f %1.2f %1.2f",
            0.5, 1.5, 2.5, 1.25, 1.75, 0.125, 0.375, -0.5, -1.5, -2.5, -1.25, -1.75, -0.125, -0.375);
    if (strcmp(buffer, "0 2 2 1.2 1.8 0.12 0.38 0 -2 -2 -1.2 -1.8 -0.12 -0.38") == 0 ||
        strcmp(buffer, "0 2 2 1.2 1.8 0.12 0.38 -0 -2 -2 -1.2 -1.8 -0.12 -0.38") == 0) {
      fputs("#define ROUND_HALF_TO_EVEN\n", versionFile);
    } else if (strcmp(buffer, "1 2 3 1.3 1.8 0.13 0.38 -1 -2 -3 -1.3 -1.8 -0.13 -0.38") == 0) {
      fputs("#define ROUND_HALF_AWAY_FROM_ZERO\n", versionFile);
    } else if (strcmp(buffer, "1 2 3 1.3 1.8 0.13 0.38 0 -1 -2 -1.2 -1.7 -0.12 -0.37") == 0 ||
               strcmp(buffer, "1 2 3 1.3 1.8 0.13 0.38 -0 -1 -2 -1.2 -1.7 -0.12 -0.37") == 0) {
      fputs("#define ROUND_HALF_UP\n", versionFile);
    } /* if */
    sprintf(buffer, "%1.14e", 1.12345678901234);
    fprintf(versionFile, "#define DOUBLE_DECIMAL_EXPONENT_DIGITS %u\n", (unsigned int) strlen(buffer) - 18);
    fprintf(versionFile, "#define FLOAT_STR_FORMAT \"%%1.%de\"\n", FLT_DIG - 1);
    fprintf(versionFile, "#define FLOAT_STR_LARGE_NUMBER 1.0e%d\n", FLT_DIG);
    fprintf(versionFile, "#define DOUBLE_STR_FORMAT \"%%1.%de\"\n", DBL_DIG - 1);
    fprintf(versionFile, "#define DOUBLE_STR_LARGE_NUMBER 1.0e%d\n", DBL_DIG);
    if (!compileAndLinkOk("#include<stdio.h>\n"
                          "int main(int argc,char *argv[]){"
                          "printf(\"%f\", 1.0/0.0);return 0;}\n") ||
        !compileAndLinkOk("#include<stdlib.h>\n#include<stdio.h>\n#include<float.h>\n#include<signal.h>\n"
                          "void handleSig(int sig){puts(\"2\");exit(0);}\n"
                          "int main(int argc,char *argv[]){\n"
#ifdef TURN_OFF_FP_EXCEPTIONS
                          "_control87(MCW_EM, MCW_EM);\n"
#endif
                          "signal(SIGFPE,handleSig);\nsignal(SIGILL,handleSig);\nsignal(SIGINT,handleSig);\n"
                          "printf(\"%d\\n\",1.0/0.0==0.0);return 0;}\n") || doTest() == 2) {
      fputs("#define FLOAT_ZERO_DIV_ERROR\n", versionFile);
    } /* if */
    if (!compileAndLinkOk("#include<stdlib.h>\n#include<stdio.h>\n#include<float.h>\n#include<signal.h>\n"
                          "void handleSig(int sig){puts(\"2\");exit(0);}\n"
                          "int main(int argc,char *argv[]){\n"
                          "float zero=0.0;\n"
#ifdef TURN_OFF_FP_EXCEPTIONS
                          "_control87(MCW_EM, MCW_EM);\n"
#endif
                          "signal(SIGFPE,handleSig);\nsignal(SIGILL,handleSig);\nsignal(SIGINT,handleSig);\n"
                          "printf(\"%d\\n\",1.0/zero==0.0);return 0;}\n") || doTest() == 2) {
      fputs("#define CHECK_FLOAT_DIV_BY_ZERO\n", versionFile);
      zero_divide_triggers_signal = 1;
      if (sizeof(float) == sizeof(int)) {
        union {
          unsigned int i;
          float f;
        } transfer;
        transfer.i = 0xffc00000;
        nanValue1 = transfer.f;
        transfer.i = 0x7f800000;
        plusInf = transfer.f;
        transfer.i = 0xff800000;
        minusInf = transfer.f;
        transfer.i = 0x80000000;
        negativeZero = transfer.f;
      } else if (sizeof(float) == sizeof(long)) {
        union {
          unsigned long i;
          float f;
        } transfer;
        transfer.i = 0xffc00000;
        nanValue1 = transfer.f;
        transfer.i = 0x7f800000;
        plusInf = transfer.f;
        transfer.i = 0xff800000;
        minusInf = transfer.f;
        transfer.i = 0x80000000;
        negativeZero = transfer.f;
      } /* if */
      nanValue2 = nanValue1;
    } else {
      nanValue1 = 0.0 / zero;
      nanValue2 = 0.0 / zero;
      plusInf = 1.0 / zero;
      minusInf = -plusInf;
      negativeZero = -1.0 / plusInf;
      if (plusInf == minusInf || -1.0 / zero != minusInf) {
        fputs("#define CHECK_FLOAT_DIV_BY_ZERO\n", versionFile);
      } /* if */
    } /* if */
    if (0.0 * plusInf != nanValue1 || 0.0 * minusInf != nanValue1 ||
        plusInf * 0.0 != nanValue1 || minusInf * 0.0 != nanValue1) {
      fputs("#define FLOAT_ZERO_TIMES_INFINITE_WRONG\n", versionFile);
    } /* if */
    if (nanValue1 == nanValue2 ||
        nanValue1 <  nanValue2 || nanValue1 >  nanValue2 ||
        nanValue1 <= nanValue2 || nanValue1 >= nanValue2) {
      fputs("#define NAN_COMPARISON_WRONG\n", versionFile);
    } /* if */
    minusZero = -zero;
    if (zero_divide_triggers_signal ||
        memcmp(&negativeZero, &minusZero, sizeof(float)) != 0) {
      fputs("#define USE_NEGATIVE_ZERO_BITPATTERN\n", versionFile);
    } /* if */
    if (pow(zero, -2.0) != plusInf || pow(negativeZero, -1.0) != minusInf) {
      fputs("#define POWER_OF_ZERO_WRONG\n", versionFile);
    } /* if */
    if (!compileAndLinkOk("#include<float.h>\n#include<math.h>\nint main(int argc,char *argv[])"
                          "{float f=0.0; isnan(f); return 0;}\n") &&
        compileAndLinkOk("#include<float.h>\n#include<math.h>\nint main(int argc,char *argv[])"
                         "{float f=0.0; _isnan(f); return 0;}\n")) {
      fputs("#define ISNAN_WITH_UNDERLINE\n", versionFile);
    } /* if */
    if (!compileAndLinkOk("#include<float.h>\n#include<math.h>\nint main(int argc,char *argv[])"
                          "{float f=0.0; isinf(f); return 0;}\n") &&
        compileAndLinkOk("#include<float.h>\n#include<math.h>\nint main(int argc,char *argv[])"
                         "{float f=0.0; _isinf(f); return 0;}\n")) {
      fputs("#define isinf _isinf\n", versionFile);
    } /* if */
    if (compileAndLinkOk("#include<stdlib.h>\n#include<stdio.h>\n#include<float.h>\n#include<signal.h>\n"
                         "void handleSig(int sig){puts(\"2\");exit(0);}\n"
                         "int main(int argc,char *argv[]){\n"
                         "float zero=1.0E37;\n"
#ifdef TURN_OFF_FP_EXCEPTIONS
                         "_control87(MCW_EM, MCW_EM);\n"
#endif
                         "signal(SIGFPE,handleSig);\nsignal(SIGILL,handleSig);\nsignal(SIGINT,handleSig);\n"
                         "printf(\"%d\\n\",(int) 1.0E37);return 0;}\n")) {
      testResult = doTest();
      if ((sizeof(int) == 4 && (long) testResult == 2147483647L) ||
          (sizeof(int) == 2 && testResult == 32767)) {
        fputs("#define FLOAT_TO_INT_OVERFLOW_SATURATES\n", versionFile);
      } else if (testResult == 2) {
        fputs("#define FLOAT_TO_INT_OVERFLOW_SIGNALS\n", versionFile);
      } else if (testResult == 0) {
        fputs("#define FLOAT_TO_INT_OVERFLOW_ZERO\n", versionFile);
      } else {
        fprintf(versionFile, "#define FLOAT_TO_INT_OVERFLOW_GARBAGE %d\n", testResult);
      } /* if */
    } /* if */
#if FLT_RADIX == 2
    floatRadixFactor = 1;
#elif FLT_RADIX == 4
    floatRadixFactor = 2;
#elif FLT_RADIX == 8
    floatRadixFactor = 3;
#elif FLT_RADIX == 16
    floatRadixFactor = 4;
#endif
    fprintf(versionFile, "#define FLOAT_MANTISSA_FACTOR %0.1f\n", pow((double) FLT_RADIX, (double) FLT_MANT_DIG));
    fprintf(versionFile, "#define FLOAT_MANTISSA_SHIFT %u\n", FLT_MANT_DIG * floatRadixFactor);
    fprintf(versionFile, "#define DOUBLE_MANTISSA_FACTOR %0.1f\n", pow((double) FLT_RADIX, (double) DBL_MANT_DIG));
    fprintf(versionFile, "#define DOUBLE_MANTISSA_SHIFT %u\n", DBL_MANT_DIG * floatRadixFactor);
    printf(" determined\n");
  } /* numericProperties */



void determineMallocAlignment (FILE *versionFile)

  {
    int count;
    unsigned long malloc_result;
    int alignment;
    int minAlignment = 7;

  /* determineMallocAlignment */
    for (count = 1; count <= 64; count++) {
      malloc_result = (unsigned long) (size_t) malloc(count);
      alignment = alignmentTable[malloc_result & 0x3f];
      if (alignment < minAlignment) {
        minAlignment = alignment;
      } /* if */
    } /* for */
    fprintf(versionFile, "#define MALLOC_ALIGNMENT %d\n", minAlignment);
  } /* determineMallocAlignment */



void checkForLimitedStringLiteralLength (FILE *versionFile)
  {
    const char *programStart = "#include <stdio.h>\n#include <string.h>\n"
                               "int main(int argc, char *argv[]){\n"
                               "char *stri =\n";
    const char *line = "\"1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890\"\n";
    const char *programEnd = "; printf(\"%d\\n\", strlen(stri) != 0); return 0;}\n";
    const int repeatCount = 1000; /* Corresponds to a string literal length of 100000. */
    int lineLength;
    int totalLength;
    int count;
    char *buffer;
    char *bufPos;

  /* checkForLimitedStringLiteralLength */
    lineLength = strlen(line);
    totalLength = strlen(programStart) + lineLength * repeatCount + strlen(programEnd);
    buffer = (char *) malloc((totalLength + 1) * sizeof(char));
    strcpy(buffer, programStart);
    bufPos = &buffer[strlen(buffer)];
    for (count = 1; count <= repeatCount; count++) {
      strcpy(bufPos, line);
      bufPos += lineLength;
    } /* for */
    strcpy(bufPos, programEnd);
    /* printf("%s\n", buffer); */
    /* Some C compilers limit the maximum string literal length. */
    /* There are limits of 2,048 bytes and 16,384 (16K) bytes.   */
    if (!compileAndLinkOk(buffer)) {
      /* A string literal of size repeatCount * lineLength is not accepted. */
      fputs("#define LIMITED_CSTRI_LITERAL_LEN\n", versionFile);
    } /* if */
    free(buffer);
  } /* checkForLimitedStringLiteralLength */



void checkMoveDirectory (FILE *versionFile)

  {
    int pos;
    FILE *aFile;
    char *buffer[1024];
    int okay = 1;

  /* checkMoveDirectory */
    mkdir("test_dir1", 0755);
    mkdir("test_dir1/subdir1", 0755);
    aFile = fopen("test_dir1/subdir1/subfile", "w");
    if (aFile != NULL) {
      fprintf(aFile, "File content\n");
      fclose(aFile);
    } /* if */
    mkdir("test_dir2", 0755);
    if (rename("test_dir1/subdir1", "test_dir2/subdir2") != 0) {
      okay = 0;
    } /* if */
    if (fileIsDir("test_dir1/subdir1")) {
      okay = 0;
      if (fileIsRegular("test_dir1/subdir1/subfile")) {
        remove("test_dir1/subdir1/subfile");
      } /* if */
      rmdir("test_dir1/subdir1");
    } /* if */
    if (fileIsDir("test_dir2/subdir2")) {
      if (fileIsRegular("test_dir2/subdir2/subfile")) {
        aFile = fopen("test_dir2/subdir2/subfile", "r");
        if (aFile == NULL) {
          okay = 0;
        } else {
          if (fread(buffer, 1, 13, aFile) != 13 ||
              memcmp(buffer, "File content\n", 13) != 0) {
            okay = 0;
          } /* if */
          fclose(aFile);
        } /* if */
        remove("test_dir2/subdir2/subfile");
      } else {
        okay = 0;
      } /* if */
      rmdir("test_dir2/subdir2");
    } else {
      okay = 0;
    } /* if */
    rmdir("test_dir1");
    rmdir("test_dir2");
    if (!okay) {
      fputs("#define MOVE_DIR_WITH_RENAME_FAILS\n", versionFile);
    } /* if */
  } /* checkMoveDirectory */



void detemineStackDirection (FILE *versionFile)

  {
    char aVariable;

  /* detemineStackDirection */
    if (stack_base < &aVariable) {
      fputs("#define STACK_GROWS_UPWARD\n", versionFile);
    } else {
      fputs("#define STACK_GROWS_DOWNWARD\n", versionFile);
    } /* if */
  } /* detemineStackDirection */



void appendToFile (const char *fileName, const char *data)

  {
    FILE *outFile;

  /* appendToFile */
    outFile = fopen(fileName, "a");
    if (outFile != NULL) {
      fputs(data, outFile);
      fclose(outFile);
    } /* if */
  } /* appendToFile */



void escapeString (FILE *versionFile, const char *text)

  { /* escapeString */
    while (*text != '\0') {
      if (*text == '\"' || *text == '\\') {
        putc('\\', versionFile);
      } /* if */
      putc(*text, versionFile);
      text++;
    } /* while */
  } /* escapeString */



#ifdef WITH_SQL
void detemineMySqlDefines (FILE *versionFile,
    char *include_options, char *system_db_libs)

  {
    const char *dbHomeSys[] = {"MariaDB/MariaDB C Client Library",
                               "MySQL/MySQL Connector C 6.1"};
    const char *dllNameList[] = {"libmariadb.dll", "libmysql.dll"};
    const char *libNameList[] = {"mariadbclient.lib", "vs11/mysqlclient.lib"};
    const char *programFilesX86 = NULL;
    const char *programFiles = NULL;
    const char *dllName = NULL;
    const char *libName = NULL;
    char dbHome[4096];
    char buffer[4096];
    int dbHomeExists = 0;
    int idx;

  /* detemineMySqlDefines */
    if (compileAndLinkOk("#include <mysql/mysql.h>\nint main(int argc,char *argv[]){return 0;}\n")) {
      printf("MySql/MariaDb found at: %s\n", "mysql/mysql.h");
      fputs("#define MYSQL_INCLUDE \"mysql/mysql.h\"\n", versionFile);
#ifdef MYSQL_DLL
      fprintf(versionFile, "#define MYSQL_DLL \"%s\"\n", MYSQL_DLL);
#elif defined MYSQL_LIBS
      if (system_db_libs[0] != '\0') {
        strcat(system_db_libs, " ");
      } /* if */
      strcat(system_db_libs, MYSQL_LIBS);
#endif
    } else {
      programFilesX86 = getenv("ProgramFiles(x86)");
      programFiles = getenv("ProgramFiles");
      if (programFiles != NULL) {
        if (sizeof(char *) == 4 && programFilesX86 != NULL) {
          programFiles = programFilesX86;
        } /* if */
        for (idx = 0; !dbHomeExists && idx < sizeof(dbHomeSys) / sizeof(char *); idx++) {
          sprintf(dbHome, "%s/%s", programFiles, dbHomeSys[idx]);
          if (fileIsDir(dbHome)) {
            dbHomeExists = 1;
          } /* if */
        } /* for */
      } /* if */
      if (dbHomeExists) {
        /* printf("dbHome=%s\n", dbHome); */
        sprintf(buffer, "-I\"%s/include\"", dbHome);
        /* printf("buffer=%s\n", buffer); */
        if (compileAndLinkWithOptionsOk("#include \"mysql.h\"\nint main(int argc,char *argv[]){return 0;}\n",
                                        buffer)) {
          printf("MySql/MariaDb found at: %s\n", dbHome);
          fputs("#define MYSQL_INCLUDE \"mysql.h\"\n", versionFile);
          if (include_options[0] != '\0') {
            strcat(include_options, " ");
          } /* if */
          strcat(include_options, buffer);
#ifdef MYSQL_DLL
          for (idx = 0; dllName == NULL && idx < sizeof(dllNameList) / sizeof(char *); idx++) {
            sprintf(buffer, "%s/lib/%s", dbHome, dllNameList[idx]);
            if (fileIsRegular(buffer)) {
              dllName = dllNameList[idx];
            } /* if */
          } /* for */
          if (dllName != NULL) {
            printf("MySql/MariaDb: %s found at: %s\n", dllName, buffer);
            fprintf(versionFile, "#define MYSQL_DLL_PATH \"");
            escapeString(versionFile, buffer);
            fprintf(versionFile, "\"\n");
            fprintf(versionFile, "#define MYSQL_DLL \"%s\"\n", dllName);
          } /* if */
#else
          for (idx = 0; libName == NULL && idx < sizeof(libNameList) / sizeof(char *); idx++) {
            sprintf(buffer, "%s/lib/%s", dbHome, libNameList[idx]);
            if (fileIsRegular(buffer)) {
              libName = libNameList[idx];
            } /* if */
          } /* for */
          if (libName != NULL) {
            sprintf(buffer, "\"%s/lib/%s\"", dbHome, libName);
            if (system_db_libs[0] != '\0') {
              strcat(system_db_libs, " ");
            } /* if */
            strcat(system_db_libs, buffer);
          } /* if */
#endif
	} /* if */
      } /* if */
    } /* if */
  } /* detemineMySqlDefines */



void deteminePostgresDefines (FILE *versionFile,
    char *include_options, char *system_db_libs)

  {
    const char *dbHomeSys[] = {"PostgreSQL/9.4", "PostgreSQL/9.3", "PostgreSQL/9.2",
                               "PostgreSQL/9.1", "PostgreSQL/9.0", "PostgreSQL/8.4",
                               "PostgreSQL/8.3"};
    const char *dllNameList[] = {"libpq.dll"};
    const char *libNameList[] = {"libpq.lib"};
    const char *libIntlDllList[] = {"libintl.dll", "libintl-8.dll"};
    const char *programFilesX86 = NULL;
    const char *programFiles = NULL;
    const char *dllName = NULL;
    const char *libName = NULL;
    char dbHome[4096];
    char buffer[4096];
    int dbHomeExists = 0;
    int idx;

  /* deteminePostgresDefines */
    if (compileAndLinkOk("#include <postgresql/libpq-fe.h>\nint main(int argc,char *argv[]){return 0;}\n")) {
      printf("PostgreSQL found at: %s\n", "postgresql/libpq-fe.h");
      fputs("#define POSTGRESQL_INCLUDE \"postgresql/libpq-fe.h\"\n", versionFile);
      if (include_options[0] != '\0') {
        strcat(include_options, " ");
      } /* if */
      strcat(include_options, "-I/usr/include/postgresql");
#ifdef POSTGRESQL_DLL
      fprintf(versionFile, "#define POSTGRESQL_DLL \"%s\"\n", POSTGRESQL_DLL);
#elif defined POSTGRESQL_LIBS
      if (system_db_libs[0] != '\0') {
        strcat(system_db_libs, " ");
      } /* if */
      strcat(system_db_libs, POSTGRESQL_LIBS);
#endif
    } else {
      programFilesX86 = getenv("ProgramFiles(x86)");
      programFiles = getenv("ProgramFiles");
      if (programFiles != NULL) {
        if (sizeof(char *) == 4 && programFilesX86 != NULL) {
          programFiles = programFilesX86;
        } /* if */
        for (idx = 0; !dbHomeExists && idx < sizeof(dbHomeSys) / sizeof(char *); idx++) {
          sprintf(dbHome, "%s/%s", programFiles, dbHomeSys[idx]);
          if (fileIsDir(dbHome)) {
            dbHomeExists = 1;
          } /* if */
        } /* for */
      } /* if */
      if (dbHomeExists) {
        /* printf("dbHome=%s\n", dbHome); */
        sprintf(buffer, "-I\"%s/include\"", dbHome);
        /* printf("buffer=%s\n", buffer); */
        if (compileAndLinkWithOptionsOk("#include \"libpq-fe.h\"\nint main(int argc,char *argv[]){return 0;}\n",
                                        buffer)) {
          printf("PostgreSQL found at: %s\n", dbHome);
          fputs("#define POSTGRESQL_INCLUDE \"libpq-fe.h\"\n", versionFile);
          if (include_options[0] != '\0') {
            strcat(include_options, " ");
          } /* if */
          strcat(include_options, buffer);
#ifdef POSTGRESQL_DLL
          for (idx = 0; dllName == NULL && idx < sizeof(dllNameList) / sizeof(char *); idx++) {
            sprintf(buffer, "%s/lib/%s", dbHome, dllNameList[idx]);
            if (fileIsRegular(buffer)) {
              dllName = dllNameList[idx];
            } /* if */
          } /* for */
          if (dllName != NULL) {
            printf("PostgreSQL: %s found at: %s\n", dllName, buffer);
            fprintf(versionFile, "#define POSTGRESQL_DLL_PATH \"");
            escapeString(versionFile, buffer);
            fprintf(versionFile, "\"\n");
            fprintf(versionFile, "#define POSTGRESQL_DLL \"%s\"\n", dllName);
          } /* if */
          dllName = NULL;
          for (idx = 0; dllName == NULL && idx < sizeof(libIntlDllList) / sizeof(char *); idx++) {
            sprintf(buffer, "%s/bin/%s", dbHome, libIntlDllList[idx]);
            if (fileIsRegular(buffer)) {
              dllName = libIntlDllList[idx];
            } /* if */
          } /* for */
          if (dllName != NULL) {
            printf("PostgreSQL: %s found at: %s\n", dllName, buffer);
            fprintf(versionFile, "#define LIBINTL_DLL_PATH \"");
            escapeString(versionFile, buffer);
            fprintf(versionFile, "\"\n");
            fprintf(versionFile, "#define LIBINTL_DLL \"%s\"\n", dllName);
          } /* if */
#else
          for (idx = 0; libName == NULL && idx < sizeof(libNameList) / sizeof(char *); idx++) {
            sprintf(buffer, "%s/lib/%s", dbHome, libNameList[idx]);
            if (fileIsRegular(buffer)) {
              libName = libNameList[idx];
            } /* if */
          } /* for */
          if (libName != NULL) {
            sprintf(buffer, "\"%s/lib/%s\"", dbHome, libName);
            if (system_db_libs[0] != '\0') {
              strcat(system_db_libs, " ");
            } /* if */
            strcat(system_db_libs, buffer);
          } /* if */
#endif
	} /* if */
      } /* if */
    } /* if */
  } /* deteminePostgresDefines */



void detemineOdbcDefines (FILE *versionFile,
    char *include_options, char *system_db_libs)

  {
    int odbc_present = 0;

  /* detemineOdbcDefines */
    if (compileAndLinkOk("#include <windows.h>\n#include <sql.h>\nint main(int argc,char *argv[]){return 0;}\n")) {
      fputs("#define WINDOWS_ODBC\n", versionFile);
      odbc_present = 1;
    } else if (compileAndLinkOk("#include <sql.h>\nint main(int argc,char *argv[]){return 0;}\n")) {
      odbc_present = 1;
    } /* if */
    if (odbc_present) {
      printf("Odbc found\n");
      fputs("#define ODBC_INCLUDE \"sql.h\"\n", versionFile);
#ifdef ODBC_DLL
      fprintf(versionFile, "#define ODBC_DLL \"%s\"\n", ODBC_DLL);
#elif defined ODBC_LIBS
      if (system_db_libs[0] != '\0') {
        strcat(system_db_libs, " ");
      } /* if */
      strcat(system_db_libs, ODBC_LIBS);
#endif
    } /* if */
  } /* detemineOdbcDefines */



void detemineOciDefines (FILE *versionFile,
    char *include_options, char *system_db_libs)

  {
    char *oracle_home;
    const char *oci_incl_dir[] = {"/rdbms/public", "/oci/include"};
    const char *oci_dll_dir[] = {"/lib", "/bin"};
    char incl_path[4096];
    char dll_path[4096];
    char buffer[4096];
    int incl_idx;
    int dll_idx;
    int opt_idx;
    char *db_libs;
    int found = 0;

  /* detemineOciDefines */
    if ((oracle_home = getenv("ORACLE_HOME")) != NULL) {
      /* printf("ORACLE_HOME=%s\n", oracle_home); */
      for (incl_idx = 0; !found && incl_idx < sizeof(oci_incl_dir) / sizeof(char *); incl_idx++) {
        sprintf(incl_path, "%s%s/oci.h", oracle_home, oci_incl_dir[incl_idx]);
        if (fileIsRegular(incl_path)) {
          sprintf(buffer, "-I%s%s", oracle_home, oci_incl_dir[incl_idx]);
          if (compileAndLinkWithOptionsOk("#include \"oci.h\"\nint main(int argc,char *argv[]){return 0;}\n",
                                           buffer)) {
            printf("Oracle found at: %s\n", oracle_home);
            fputs("#define OCI_INCLUDE \"oci.h\"\n", versionFile);
            sprintf(buffer, "-I%s%s", oracle_home, oci_incl_dir[incl_idx]);
            if (include_options[0] != '\0') {
              strcat(include_options, " ");
            } /* if */
            strcat(include_options, buffer);
#ifdef OCI_DLL
            fprintf(versionFile, "#define OCI_DLL \"%s\"\n", OCI_DLL);
            for (dll_idx = 0; !found && dll_idx < sizeof(oci_dll_dir) / sizeof(char *); dll_idx++) {
              sprintf(dll_path, "%s%s", oracle_home, oci_dll_dir[dll_idx]);
              if (fileIsDir(dll_path)) {
                sprintf(buffer, "%s%s/%s", oracle_home, oci_dll_dir[dll_idx], OCI_DLL);
                if (fileIsRegular(buffer)) {
                  sprintf(buffer, "-Wl,-rpath=%s%s", oracle_home, oci_dll_dir[dll_idx]);
                  if (system_db_libs[0] != '\0') {
                    strcat(system_db_libs, " ");
                  } /* if */
                  strcat(system_db_libs, buffer);
                  found = 1;
                } /* if */
              } /* if */
            } /* for */
#endif
            found = 1;
          } /* if */
        } /* if */
      } /* for */
    } /* if */
  } /* detemineOciDefines */
#endif



void detemineDatabaseDefines (FILE *versionFile)

  {
    char *include_opt;
    char *db_libs;
    char include_options[4096];
    char system_db_libs[4096];
    char buffer[4096];

  /* detemineDatabaseDefines */
    include_options[0] = '\0';
    system_db_libs[0] = '\0';
#ifdef WITH_SQL
    detemineMySqlDefines(versionFile, include_options, system_db_libs);
    deteminePostgresDefines(versionFile, include_options, system_db_libs);
    detemineOdbcDefines(versionFile, include_options, system_db_libs);
    detemineOciDefines(versionFile, include_options, system_db_libs);
    if (compileAndLinkOk("#include <sqlite3.h>\nint main(int argc,char *argv[]){return 0;}\n")) {
      fputs("#define SQLITE_INCLUDE \"sqlite3.h\"\n", versionFile);
#ifdef SQLITE_LIBS
      db_libs = SQLITE_LIBS;
#else
      db_libs = "-lsqlite3";
#endif
      if (system_db_libs[0] != '\0') {
        strcat(system_db_libs, " ");
      } /* if */
      strcat(system_db_libs, db_libs);
    } /* if */
    sprintf(buffer, "INCLUDE_OPTIONS = %s\n", include_options);
    appendToFile("macros", buffer);
    sprintf(buffer, "SYSTEM_DB_LIBS = %s\n", system_db_libs);
    appendToFile("macros", buffer);
#endif
    fprintf(versionFile, "#define INCLUDE_OPTIONS \"");
    escapeString(versionFile, include_options);
    fprintf(versionFile, "\"\n");
    fprintf(versionFile, "#define SYSTEM_DB_LIBS \"");
    escapeString(versionFile, system_db_libs);
    fprintf(versionFile, "\"\n");
  } /* detemineDatabaseDefines */



/**
 *  Program to Check properties of C compiler and runtime.
 */
int main (int argc, char **argv)

  {
    FILE *versionFile = NULL;
    char aVariable;
    FILE *aFile;
    time_t timestamp;
    struct tm *local_time;
    char buffer[4096];
    int ch;
    union {
      char           charValue;
      unsigned long  genericValue;
    } testUnion;
    int testResult;
    const char *define_read_buffer_empty;

  /* main */
    if (argc >= 1) {
      versionFile = fopen(argv[1], "a");
    } /* if */
    if (versionFile == NULL) {
      versionFile = stdout;
    } /* if */
    prepareCompileCommand();
#ifdef WRITE_CC_VERSION_INFO
    WRITE_CC_VERSION_INFO
#endif
    aFile = fopen("cc_vers.txt", "r");
    if (aFile != NULL) {
      fprintf(versionFile, "#define C_COMPILER_VERSION \"");
      for (ch=getc(aFile); ch != EOF && ch != 10 && ch != 13; ch = getc(aFile)) {
        if (ch >= ' ' && ch <= '~') {
          if (ch == '\"' || ch == '\'' || ch == '\\') {
            putc('\\', versionFile);
          } /* if */
          putc(ch, versionFile);
        } else {
          fprintf(versionFile, "\\%3o", ch);
        } /* if */
      } /* for */
      fputs("\"\n", versionFile);
      fclose(aFile);
    } /* if */
    if (compileAndLinkOk("#include <unistd.h>\nint main(int argc,char *argv[]){return 0;}\n")) {
      fputs("#define UNISTD_H_PRESENT\n", versionFile);
    } /* if */
    if (!compileAndLinkOk("static inline int test(int a){return 2*a;}\n"
                          "int main(int argc,char *argv[]){return test(argc);}\n")) {
      fputs("#define inline\n", versionFile);
    } /* if */
    if (!compileAndLinkOk("int test (int *restrict ptrA, int *restrict ptrB, int *restrict ptrC)\n"
                          "{*ptrA += *ptrC; *ptrB += *ptrC; return *ptrA+ptrB;}\n"
                          "int main(int argc,char *argv[])\n"
                          "{int a=1, b=2, c=3; return test(&a, &b, &c);}\n")) {
      fputs("#define restrict\n", versionFile);
    } /* if */
    buffer[0] = '\0';
    if (compileAndLinkOk("#include <stdio.h>\nint main(int argc,char *argv[])\n"
                         "{if(__builtin_expect(1,1))puts(\"1\");else puts(\"0\");return 0;}\n")) {
      fputs("#define likely(x)   __builtin_expect((x),1)\n", versionFile);
      fputs("#define unlikely(x) __builtin_expect((x),0)\n", versionFile);
      strcat(buffer, "#define likely(x)   __builtin_expect((x),1)\\n");
      strcat(buffer, "#define unlikely(x) __builtin_expect((x),0)\\n");
    } else {
      strcat(buffer, "#define likely(x) (x)\\n");
      strcat(buffer, "#define unlikely(x) (x)\\n");
    } /* if */
    if (compileAndLinkOk("#include <stdlib.h>\n"
                         "void fatal (void) __attribute__ ((noreturn));\n"
                         "void fatal (void) {exit(1);}\n"
                         "int main(int argc,char *argv[])\n"
                         "{return 0;}\n")) {
      fputs("#define NORETURN __attribute__ ((noreturn))\n", versionFile);
      strcat(buffer, "#define NORETURN __attribute__ ((noreturn))\\n");
    } else {
      strcat(buffer, "#define NORETURN\\n");
    } /* if */
    fprintf(versionFile, "#define MACRO_DEFS \"%s\"\n", buffer);
    if (compileAndLinkOk("#include <stdio.h>\nint main(int argc, char *argv[])\n"
                         "{FILE *aFile; aFile=popen(\""
                         LIST_DIRECTORY_CONTENTS
                         "\", \"r\");\n"
                         "printf(\"%d\\n\", ftell(aFile) != -1); return 0;}\n") ||
        compileAndLinkOk("#include <stdio.h>\nint main(int argc, char *argv[])\n"
                         "{FILE *aFile; aFile=_popen(\""
                         LIST_DIRECTORY_CONTENTS
                         "\", \"r\");\n"
                         "printf(\"%d\\n\", ftell(aFile) != -1); return 0;}\n")) {
      if (doTest() == 1) {
        fputs("#define FTELL_WRONG_FOR_PIPE\n", versionFile);
      } /* if */
    } else {
      fputs("#define POPEN_MISSING\n", versionFile);
    } /* if */
    if ((aFile = fopen("tmp_test_file","w")) != NULL) {
      fwrite("asdf",1,4,aFile);
      fclose(aFile);
      if ((aFile = fopen("tmp_test_file","r")) != NULL) {
        if (fwrite("qwert",1,5,aFile) != 0) {
          fputs("#define FWRITE_WRONG_FOR_READ_ONLY_FILES\n", versionFile);
        } /* if */
        fclose(aFile);
      } /* if */
      remove("tmp_test_file");
    } /* if */
    mkdir("tmp_empty_dir", 0755);
    if (compileAndLinkOk(
        "#include <stdio.h>\n#include <utime.h>\n#include <errno.h>\nint main(int argc,char *argv[])"
        "{struct utimbuf utime_buf;\n"
        "utime_buf.actime=1234567890;utime_buf.modtime=1234567890;\n"
        "printf(\"%d\\n\",utime(\"tmp_empty_dir\",&utime_buf)!=0&&errno==EACCES);return 0;}\n") &&
        doTest() == 1) {
      fputs("#define USE_ALTERNATE_UTIME\n", versionFile);
#ifdef os_utime
      fprintf(versionFile, "#define os_utime_orig %s\n", xstr(os_utime));
      fputs("#undef os_utime\n", versionFile);
#else
      fputs("#define os_utime_orig utime\n", versionFile);
#endif
      fputs("#define os_utime alternate_utime\n", versionFile);
    } else if (compileAndLinkOk(
        "#include <stdio.h>\n#include <sys/utime.h>\n#include <errno.h>\nint main(int argc,char *argv[])"
        "{struct utimbuf utime_buf;\n"
        "utime_buf.actime=1234567890;utime_buf.modtime=1234567890;\n"
        "printf(\"%d\\n\",utime(\"tmp_empty_dir\",&utime_buf)!=0&&errno==EACCES);return 0;}\n") &&
        doTest() == 1) {
      fputs("#define INCLUDE_SYS_UTIME\n", versionFile);
      fputs("#define USE_ALTERNATE_UTIME\n", versionFile);
#ifdef os_utime
      fprintf(versionFile, "#define os_utime_orig %s\n", xstr(os_utime));
      fputs("#undef os_utime\n", versionFile);
#else
      fputs("#define os_utime_orig utime\n", versionFile);
#endif
      fputs("#define os_utime alternate_utime\n", versionFile);
    } /* if */
    if (remove("tmp_empty_dir") != 0) {
      fputs("#define REMOVE_FAILS_FOR_EMPTY_DIRS\n", versionFile);
      rmdir("tmp_empty_dir");
    } /* if */
    checkMoveDirectory(versionFile);
    if (compileAndLinkOk("#include <stdio.h>\n#include <errno.h>\nint main(int argc,char *argv[])"
                         "{int saved_errno=EXDEV; printf(\"%d\\n\",saved_errno); return 0;}\n")) {
      fputs("#define EXDEV_IS_DEFINED\n", versionFile);
    } /* if */
#if defined OS_STRI_WCHAR && defined USE_WINSOCK
    /* Under Windows a rename between different    */
    /* devices fails with EACCES instead of EXDEV. */
    fputs("#define USE_EACCES_INSTEAD_OF_EXDEV\n", versionFile);
    /* Windows uses pending deletes which cause    */
    /* problems when a file with the same name is  */
    /* created shortly after the delete. To avoid  */
    /* problems files are renamed before they are  */
    /* removed.                                    */
    fputs("#define RENAME_BEFORE_REMOVE\n", versionFile);
#endif
    aFile = fopen(".","r");
    if (aFile != NULL) {
      fputs("#define FOPEN_OPENS_DIRECTORIES\n", versionFile);
      fclose(aFile);
    } /* if */
    numericSizes(versionFile);
    determineMallocAlignment(versionFile);
    if (compileAndLinkOk("#include<signal.h>\nint main(int argc, char *argv[]){\n"
                         "signal(SIGBUS,SIG_DFL); return 0;}\n")) {
      if (compileAndLinkOk("#include<stdlib.h>\n#include <stdio.h>\n#include<signal.h>\n"
                           "void handleSig(int sig){puts(\"2\");exit(0);}\n"
                           "int main(int argc, char *argv[]){\n"
                           "signal(SIGBUS,handleSig);\n"
                           "int p[3]={12,34,56}, q, *pp; pp=(int *)((char *)&p[1]+1); q=*pp;\n"
                           "printf(\"1\\n\"); return 0;}\n") && doTest() == 1) {
        fputs("#define UNALIGNED_MEMORY_ACCESS_OKAY\n", versionFile);
      } else {
        fputs("#define UNALIGNED_MEMORY_ACCESS_FAILS\n", versionFile);
      } /* if */
    } else {
      if (compileAndLinkOk("#include <stdio.h>\nint main(int argc, char *argv[])\n"
                           "{int p[3]={12,34,56}, q, *pp; pp=(int *)((char *)&p[1]+1); q=*pp;\n"
                           "printf(\"1\\n\"); return 0;}\n") && doTest() == 1) {
        fputs("#define UNALIGNED_MEMORY_ACCESS_OKAY\n", versionFile);
      } else {
        fputs("#define UNALIGNED_MEMORY_ACCESS_FAILS\n", versionFile);
      } /* if */
    } /* if */
    memset(&testUnion, 0, sizeof(testUnion));
    testUnion.charValue = 'X';
    if (testUnion.charValue != (char) testUnion.genericValue) {
      fputs("#define CASTING_DOES_NOT_GET_A_UNION_ELEMENT\n", versionFile);
    } /* if */
    if (EOF != -1) {
      fputs("#define EOF_IS_NOT_MINUS_ONE\n", versionFile);
    } /* if */
    if (!compileAndLinkOk("#include <stdio.h>\n"
                          "typedef struct emptyStruct { } emptyRecord;\n"
                          "int main(int argc, char *argv[]){\n"
                          "return 0;}\n")) {
      fputs("#define NO_EMPTY_STRUCTS\n", versionFile);
    } /* if */
    if (compileAndLinkOk("#include <stdio.h>\n#include <string.h>\n"
                         "int main(int argc, char *argv[]){\n"
                         "printf(\"%d\\n\", strcmp(\"\?\?(\", \"[\") == 0);\n"
                         "return 0;}\n") && doTest() == 1) {
      fputs("#define TRIGRAPH_SEQUENCES_ARE_REPLACED\n", versionFile);
    } /* if */
    checkForLimitedStringLiteralLength(versionFile);
    stack_base = &aVariable;
    detemineStackDirection(versionFile);
#ifndef STACK_SIZE
    if (sizeof(char *) == 8) { /* Machine with 64-bit addresses */
      /* Due to alignment some 64-bit machines have huge stack requirements. */
      fputs("#define STACK_SIZE 0x1000000\n", versionFile); /* 16777216 bytes */
    } /* if */
#endif
    numericProperties(versionFile);
#ifdef USE_ALTERNATE_LOCALTIME_R
    fputs("#define USE_LOCALTIME_R\n", versionFile);
    if ((time_t) -1 < 0) {
      fputs("#define LOCALTIME_WORKS_SIGNED\n", versionFile);
    } /* if */
#else
    if (compileAndLinkOk("#include<time.h>\nint main(int argc,char *argv[])"
                         "{time_t ts;struct tm res;struct tm*lt;lt=localtime_r(&ts,&res);return 0;}\n")) {
      fputs("#define USE_LOCALTIME_R\n", versionFile);
      if (compileAndLinkOk("#include<time.h>\nint main(int argc,char *argv[])"
                           "{time_t ts=-2147483647-1;struct tm res;struct tm*lt;\n"
                           "lt=localtime_r(&ts,&res);\n"
                           "printf(\"%d\\n\",lt!=NULL&&lt->tm_year==1);return 0;}\n") && doTest() == 1) {
        fputs("#define LOCALTIME_WORKS_SIGNED\n", versionFile);
      } /* if */
    } else if (compileAndLinkOk("#include<time.h>\nint main(int argc,char *argv[])"
                                "{time_t ts;struct tm res;localtime_s(&res,&ts);return 0;}\n")) {
      fputs("#define USE_LOCALTIME_S\n", versionFile);
      if (compileAndLinkOk("#include<time.h>\nint main(int argc,char *argv[])"
                           "{time_t ts=-2147483647-1;struct tm res;\n"
                           "localtime_s(&res,&ts);\n"
                           "printf(\"%d\\n\",lt!=NULL&&lt->tm_year==1);return 0;}\n") && doTest() == 1) {
        fputs("#define LOCALTIME_WORKS_SIGNED\n", versionFile);
      } /* if */
    } else {
      timestamp = -2147483647 - 1;
      local_time = localtime(&timestamp);
      if (local_time != NULL && local_time->tm_year == 1) {
        fputs("#define LOCALTIME_WORKS_SIGNED\n", versionFile);
      } /* if */
    } /* if */
#endif
    determineEnvironDefines(versionFile);
#ifdef OS_PATH_HAS_DRIVE_LETTERS
    if (getenv("USERPROFILE") != NULL) {
      /* When USERPROFILE is defined then it is used, even when HOME is defined. */
      fputs("#define HOME_DIR_ENV_VAR {'U', 'S', 'E', 'R', 'P', 'R', 'O', 'F', 'I', 'L', 'E', 0}\n", versionFile);
    } else if (getenv("HOME") != NULL) {
      fputs("#define HOME_DIR_ENV_VAR {'H', 'O', 'M', 'E', 0}\n", versionFile);
    } else {
      fputs("#define HOME_DIR_ENV_VAR {'H', 'O', 'M', 'E', 0}\n", versionFile);
      fputs("#define DEFAULT_HOME_DIR {'C', ':', '\\\\', 0}\n", versionFile);
    } /* if */
#else
    fputs("#define HOME_DIR_ENV_VAR {'H', 'O', 'M', 'E', 0}\n", versionFile);
#endif
    if (compileAndLinkOk("#include <stdlib.h>\n#include <stdio.h>\n#include <signal.h>\n"
                         "void handleSig(int sig){puts(\"1\");exit(0);}\n"
                         "int main(int argc, char *argv[]){\n"
                         "struct sigaction sig_act;\n"
                         "sig_act.sa_handler = handleSig;\n"
                         "sigemptyset(&sig_act.sa_mask);\n"
                         "sig_act.sa_flags = SA_RESTART;\n"
                         "if (sigaction(SIGINT, &sig_act, NULL) == -1)\n"
                         "{puts(\"2\");}else{raise(SIGINT);puts(\"3\");}\n"
                         "return 0;}\n") && doTest() == 1) {
      fputs("#define HAS_SIGACTION\n", versionFile);
    } /* if */
    if (compileAndLinkOk("#include <stdio.h>\n#include <sys/resource.h>\n"
                         "int main(int argc, char *argv[]){\n"
                         "struct rlimit rlim;\n"
                         "printf(\"%d\\n\", getrlimit(RLIMIT_STACK, &rlim) == 0);\n"
                         "return 0;}\n") && doTest() == 1) {
      fputs("#define HAS_GETRLIMIT\n", versionFile);
    } /* if */
    if (compileAndLinkOk("#include <stdio.h>\n#include <setjmp.h>\n"
                         "int main(int argc, char *argv[]){\n"
                         "sigjmp_buf env; int ret_code; int count = 2;\n"
                         "if ((ret_code=sigsetjmp(env, 1)) == 0) {\n"
                         "count--; siglongjmp(env, count);\n"
                         "} else printf(\"%d\\n\", ret_code);\n"
                         "return 0;}\n") && doTest() == 1) {
      fputs("#define HAS_SIGSETJMP\n", versionFile);
    } /* if */
    if (compileAndLinkOk("#include <unistd.h>\n"
                         "int main(int argc, char *argv[]){\n"
                         "char buf[256]; ssize_t link_len; int ret_code;\n"
                         "link_len=readlink(\"qwertzuiop\", buf, 256);\n"
                         "ret_code=symlink(\"qwertzuiop\", \"asdfghjkl\");\n"
                         "return 0;}\n")) {
      fputs("#define HAS_SYMLINKS\n", versionFile);
    } /* if */
    if (compileAndLinkOk("#include <sys/types.h>\n#include <sys/stat.h>\n"
                         "int main(int argc, char *argv[]){\n"
                         "int ret_code;\n"
                         "ret_code=mkfifo(\"qwertzuiop\", 0);\n"
                         "return 0;}\n")) {
      fputs("#define HAS_FIFO_FILES\n", versionFile);
    } /* if */
    if (compileAndLinkOk("#include<poll.h>\nint main(int argc,char *argv[])"
                         "{struct pollfd pollFd[1];poll(pollFd, 1, 0);return 0;}\n")) {
      fputs("#define HAS_POLL\n", versionFile);
    } /* if */
    detemineDatabaseDefines(versionFile);
    if (compileAndLinkOk("#include<stdio.h>\nint main(int argc,char *argv[]){FILE*fp;fp->_IO_read_ptr>=fp->_IO_read_end;return 0;}\n")) {
      define_read_buffer_empty = "#define read_buffer_empty(fp) ((fp)->_IO_read_ptr >= (fp)->_IO_read_end)";
    } else if (compileAndLinkOk("#include<stdio.h>\nint main(int argc,char *argv[]){FILE*fp;fp->_cnt <= 0;return 0;}\n")) {
      define_read_buffer_empty = "#define read_buffer_empty(fp) ((fp)->_cnt <= 0)";
    } else if (compileAndLinkOk("#include<stdio.h>\nint main(int argc,char *argv[]){FILE*fp;fp->__cnt <= 0;return 0;}\n")) {
      define_read_buffer_empty = "#define read_buffer_empty(fp) ((fp)->__cnt <= 0)";
    } else if (compileAndLinkOk("#include<stdio.h>\nint main(int argc,char *argv[]){FILE*fp;fp->level <= 0;return 0;}\n")) {
      define_read_buffer_empty = "#define read_buffer_empty(fp) ((fp)->level <= 0)";
    } else if (compileAndLinkOk("#include<stdio.h>\nint main(int argc,char *argv[]){FILE*fp;fp->_r <= 0;return 0;}\n")) {
      define_read_buffer_empty = "#define read_buffer_empty(fp) ((fp)->_r <= 0)";
    } else {
      define_read_buffer_empty = NULL;
    } /* if */
    if (define_read_buffer_empty != NULL) {
      strcpy(buffer, "#include<stdio.h>\n");
      strcat(buffer, define_read_buffer_empty);
      strcat(buffer, "\nint main(int argc,char *argv[])\n"
                     "{FILE*fp;fp=fopen(\"version.h\",\"r\");"
                     "if(fp==NULL||!read_buffer_empty(fp))puts(0);else{"
                     "getc(fp);printf(\"%d\\n\",read_buffer_empty(fp)?0:1);}return 0;}\n");
      if (!compileAndLinkOk(buffer) || doTest() != 1) {
        define_read_buffer_empty = NULL;
      } /* if */
    } /* if */
    if (define_read_buffer_empty != NULL) {
      fprintf(versionFile, "%s\n", define_read_buffer_empty);
    } /* if */
    cleanUpCompilation();
    return 0;
  } /* main */
